Algoritmo "Celsius_para_Fahrenheit"

Var
   c, f: real

Inicio
   escreva("Digite a temperatura em Celsius: ")
   leia(c)

   f <- (c * 9/5) + 32

   escreva("Temperatura em Fahrenheit: ", f)

Fimalgoritmo

Var                      Algoritmo "Celsius_para_Fahrenheit"

Var
   c, f: real

Inicio
   escreva("Digite a temperatura em Celsius: ")
   leia(c)

   f <- (c * 9/5) + 32

   escreva("Temperatura em Fahrenheit: ", f)

Fimalgoritmo
